### ISSUE TITLE
Examples should be collapsible

### ISSUE THREAD

**Issue by lowskidev** [open-rpc/playground#117]
Make examples section collapsible and when more than one example is given, create an arrow or indicator to show there is more then one example.

**Comment by vijya76** [comment]
Hi @ethernodeio,
 
It seems like we want the whole example section should be collapsible and wrap all the examples. And also add an arrow to the dropdown menu.  Here different arrows of dropdown and collapsible will create a confusing UX. 
Instead, I would suggest making each example a collapsible. That would also avoid confusion between elements.
