### ISSUE TITLE
Summary column is empty for referenced parameters.

### ISSUE THREAD

**Issue by malidiab** [open-rpc/playground#217]
"Summary" of a parameter field will not be displayed in the generated HTML if the parameter is referenced as a component.  ex 
` "params": [
                {
                    "name": "systemID",
                    "required": true,
                    "schema": {
                        "$ref": "#/components/SystemID"
                    }
                },
`
where 
`  "components": {
        "SystemID": {
            "type": "integer",
            "title": "System ID",
            "summary": "My SUmmary",`

it only works when I put the "summary" field directly in the parameter object in the params array. This is useful as there will always be redundant parameters, and you don't want to have redundant documentation for it.

**Comment by shanejonas** [comment]
schema doesn’t have summary,


also the components should be nested once more with “schemas” to define the re-usable schemas.


(here’s an example but i’m missing quotes since i’m typing from mobile)

components: {
  schemas: {
    SystemID: {}
  },
  contentDescriptors: {},
  examples: {}
}

**Comment by malidiab** [comment]
Makes sense , thanks !
