### ISSUE TITLE
long doc cause scroll overflow

### ISSUE THREAD

**Issue by meowsbits** [open-rpc/playground#371]
I lose my scroll bar (and indicator) with a long document. See below, it's small because you can only see the top of the indicator, and if I keep scrolling down thru the next 40% of the document it's completely invisible.

![image](https://user-images.githubusercontent.com/45600330/76703355-3ef07280-669f-11ea-8557-44fe8cc53028.png)

**Comment by shanejonas** [comment]
is this only when there are errors?

**Comment by meowsbits** [comment]
https://gist.github.com/meowsbits/509c34545389d7512938659bc36bee13

**Comment by meowsbits** [comment]
yes, is only when the error pane is open (showing list of schema errors)

**Comment by meowsbits** [comment]
Beep.
