### ISSUE TITLE
json.worker.js downloaded on each request

### ISSUE THREAD

**Issue by tarampampam** [open-rpc/playground#402]
`https://playground.open-rpc.org/json.worker.js` is static file, but on each PRC request (using playground "Play" button) this file downloaded twice.

This is required for static file?  Why do not download this file once on bootstrapping?

![screenshot](https://user-images.githubusercontent.com/7326800/79188041-733e8680-7e37-11ea-9b2c-7de325ba9db3.png)

**Comment by tarampampam** [comment]
Any news?

**Comment by tarampampam** [comment]
Any news? [2]

**Comment by tarampampam** [comment]
Any news? [3]

**Comment by zcstarr** [comment]
If you want to take a stab at this I'm fully behind it!
