### ISSUE TITLE
Playground doesn't follow "latest spec"

### ISSUE THREAD

**Issue by ulidtko** [open-rpc/playground#442]
Hi!

Not going to rant too much (although hell I'd love to); just wanted to let you know how my **first ever interaction** with OpenRPC was, past hours of reading up and research. 

I opened [the playground](https://playground.open-rpc.org), loaded & skimmed through an example, then gathered my thoughts and finally decided to give it a try. The very 1st line of the example said: `"openrpc": "1.0.0-rc1"` — *well this can't be right* I thought. *What's the latest spec version again?..* — fine, it ain't [that hard](https://github.com/open-rpc/spec/releases), 1.2.6 it is.

> `"openrpc": "1.2.6"`

![Screenshot from 2020-07-17 18-54-17](https://user-images.githubusercontent.com/365338/87807594-1b158700-c861-11ea-879d-49f2eb50ba6e.png)

I hope this gives you an idea.

**Comment by shanejonas** [comment]
@ulidtko thanks for taking the time to file this issue. I'll have a fix shortly

**Comment by shanejonas** [comment]
@ulidtko shipped 🚢  in `1.5.4`. Thanks again for taking the time to report the issue. Let us know if you hit any other issues or questions about OpenRPC!
