### ISSUE TITLE
UI: support schema.examples

### ISSUE THREAD

**Issue by meowsbits** [open-rpc/playground#496]
I'd love to see support for `schema.examples` in the playground UI. 

- https://json-schema.org/draft/2019-09/json-schema-validation.html#rfc.section.9.5
- https://spec.open-rpc.org/#example-object

![image](https://user-images.githubusercontent.com/45600330/97441760-126c2c80-18f7-11eb-8048-a700c2321b98.png)
> https://playground.open-rpc.org/?url=https://gist.githubusercontent.com/meowsbits/a1d523ee32630bfc2c7bd3b5356f2d6a/raw/lotus-openrpc-spec.json

**Comment by meowsbits** [comment]
AFAIU this has been resolved, eg.

![image](https://user-images.githubusercontent.com/45600330/103542784-18d0d480-4e63-11eb-9c4e-43ff5cb5d123.png)
> https://playground.open-rpc.org/?url=https://gist.githubusercontent.com/meowsbits/2f22b61ce46f6897d343f850ac86b540/raw/openrpc_doc.json

**Comment by shanejonas** [comment]
it is resolved but is solved better with this: https://github.com/open-rpc/schema-utils-js/pull/486

as it will handle `Try It Now` properly and anything else that arises
