### ISSUE TITLE
UI: render markdown at method description

### ISSUE THREAD

**Issue by meowsbits** [open-rpc/playground#499]
![image](https://user-images.githubusercontent.com/45600330/97902839-c4df2d80-1d03-11eb-99fa-61cd884e8ea7.png)

Would be cool to render this (codefences, etc.).

**Comment by shanejonas** [comment]
the summarys arent markdown in the spec, but `description` is

**Comment by meowsbits** [comment]
Roger that. Will close issue.

For reference, in the screenshot above, the `description` is, well, what's rendered in Markdown.
