### ISSUE TITLE
Don't auto redirect to https

### ISSUE THREAD

**Issue by lightclient** [open-rpc/playground#561]
It would be nice if the playground didn't auto redirect to https. A lot of times if we're just playing with endpoints, we don't have them setup behind and https service. Since I can only load the playground over https, it doesn't allow call over http from the page.

**Comment by shanejonas** [comment]
I think its your browser caching https, trying it in incognito lets me use `http`:

![image](https://user-images.githubusercontent.com/364566/127036917-28f22afb-3b11-4ea5-8cf8-b8257b361bd1.png)

**Comment by lightclient** [comment]
Oh interesting, that was the issue. Thank you!
